users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users.email import VerificationView
from . import views

urlpatterns = [
    # Регистрация, вход, уход с аккаунта, профиль
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    path('account/', views.EditProfile.as_view(), name='edit_profile'),

    # Сменить пароль в профиле
    path('account/password_change/', auth_views.PasswordChangeView.as_view(
                                                            template_name="users/password/password_change_form.html"),
                                                            name='password_change'),
    path('account/password_change/done/', auth_views.PasswordChangeDoneView.as_view(
                                                            template_name="users/password/password_change_done.html"),
                                                            name="password_change_done"),
    # Восстановить пароль при входе в аккаунт
    path('password_reset/', auth_views.PasswordResetView.as_view(
                                                            template_name="users/password/password_reset.html"),
                                                            name="password_reset"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                                                            template_name="users/password/password_reset_confirm.html"),
                                                            name="password_reset_confirm"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
                                                            template_name="users/password/password_reset_done.html"),
                                                            name="password_reset_done"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
                                                            template_name="users/password/password_reset_complete.html"),
                                                            name="password_reset_complete"),
    # Подтвердить аккаунт через почту
    path('activate/<uid64>/<token>/', VerificationView.as_view(), name='activate')
]

content/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.timezone import now
from django.urls import reverse


class Gender(models.Model):
    """
        Gender: Gender actor
    """
    name = models.CharField()

    class Meta:
        verbose_name = 'Gender'
        verbose_name_plural = 'Genders'

    def __str__(self):
        return self.name


class Actor(models.Model):
    """
        Actors: Information about current actor
    """
    name = models.CharField('Name and Surname', max_length=50)
    slug = models.SlugField(max_length=50, null=False, unique=True)
    gender = models.ManyToManyField(Gender, verbose_name="genders", related_name='actor_gender')
    age = models.PositiveSmallIntegerField('Age', default=0)
    birthday = models.DateField("Birthday", default=now())
    description = models.TextField(max_length=250)
    main_picture = models.ImageField('Main photo of the actor', upload_to='actors/', blank=True, null=True)

    class Meta:
        db_table = 'actor'
        verbose_name = 'Actor'
        verbose_name_plural = 'Actors'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("actor-detail", kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Genre(models.Model):
    """
        Genres: Genres for film
    """
    name = models.CharField(max_length=25)
    slug = models.SlugField(max_length=60, null=False, unique=True)

    class Meta:
        db_table = 'genre'
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'

    def __str__(self):
        return self.name


class Movie(models.Model):
    """
        Films: Set of content
    """
    name = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80, null=False, unique=True)
    description = models.TextField(max_length=250)
    genres = models.ManyToManyField(Genre, verbose_name="genres", related_name='movie_genres')
    public_date = models.DateTimeField('Date published', default=now())
    main_image = models.ImageField('Pictures', upload_to='content/', blank=True, null=True)
    actors = models.ManyToManyField(Actor, verbose_name="actors", related_name='film_actor')
    budget = models.PositiveIntegerField('Budget', default=0)
    fees = models.PositiveIntegerField('Fees', default=0)

    class Meta:
        db_table = 'movie'
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("movie_detail", kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class FootageMovie(models.Model):
    image = models.ImageField('Footage from film', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='images')


class FootageActor(models.Model):
    image = models.ImageField('Photos of the actor', upload_to='actor_shots/')
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE, related_name='images')


#
# Comment System
#

class Comment(models.Model):
    pass

templates/movies/movie-detail.html
{% extends 'base.html' %}
{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock head %}
<title>{% block title %}Tortuga - {{ movie.name }}{% endblock title %}</title>

{% block content %}
    {% for image in movie.footagemovie_set.all %}
        <img src="{{ image.image.url }}" class="movie-shots">
    {% endfor %}
{% endblock content %}

{% include 'components/ratings' %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/make_rating.js' %}"></script>
{% endblock js %}

templates/movies/movie-list.html
{% extends 'base.html' %}
<title>{% block title %}Tortuga - Movies{% endblock title %}</title>

{% block content %}
    <form action="{% url 'filter_genre' %}" method="get">
        <div id="list-example" class="list-group">
            <h3>Фильтр</h3>
            {% for genre in view.get_genres %}
                <input type="checkbox" class="checked" name="genre" value="{{ genre.name }}">
                <span class="list-group-item list-group-item-action">{{ genre.name }}</span>
            {% endfor %}
        </div>
        <button type="submit">Найти</button>
    </form>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for movie in movie_list %}
            <div class="col">
                <div class="card">
                  <img src="{{ movie.main_image.url }}" class="card-img-top" alt="Logo">
                  <div class="card-body">
                    <h5 class="card-title"><a href="{{ movie.get_absolute_url }}"></a>{{ movie.name }}</h5>
                    <p class="card-text">{{ movie.description }}</p>
                  </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

{% include 'components/pagination.html' %}

templates/movies/movie-search-list.html
{% extends 'base.html' %}
<title>{% block title %}Tortuga - Movies{% endblock title %}</title>

{% block content %}
    {% if query %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for movie in results %}
                <div class="col">
                    <div class="card">
                      <img src="{{ movie.main_image.url }}" class="card-img-top" alt="Logo">
                      <div class="card-body">
                        <h5 class="card-title"><a href="{{ movie.get_absolute_url }}"></a>{{ movie.name }}</h5>
                        <p class="card-text">{{ movie.description }}</p>
                      </div>
                    </div>
                </div>
            {% empty %}
                <h1>Результатов 0 на ваш запрос(</h1>
            {% endfor %}
        </div>
    {% endif %}
{% endblock content %}

{% include 'components/pagination.html' %}